I'd like to use this script to repair the configs
HiSPARC/datastore pull request #24
Opened 2017-04-18 12:56 UTC by kaspervd

See https://github.com/HiSPARC/datastore/issues/23

2017-04-18 13:08 UTC, tomkooij requested changes
Disregard the syntax stuff, but please backup (and verify the backup) before starting the script.

2017-04-18 13:08 UTC, tomkooij commented on migration/config-repair/remove_incorrect_configs.py
> +        config.remove_rows(1,len(config))
I think `remove_rows(2)` should be enough.
http://www.pytables.org/usersguide/libref/structured_storage.html?highlight=remove_rows#tables.Table.remove_rows

2017-04-18 13:08 UTC, tomkooij commented on migration/config-repair/remove_incorrect_configs.py
> +        config = data.get_node("/hisparc/cluster_"+cluster+"/station_"+str(stationnumber)+"/config")
`data.config('/hisaprc/cluster_%s/station_%d/config' % (cluster, stationnumber))` is much more readable. IMHO

2017-04-18 13:08 UTC, tomkooij commented on migration/config-repair/remove_incorrect_configs.py
> +    copyfile(filename, filename+'_backup')
Don't backup in your script!

Backup. Check backup. Make sure the backup is untouchable by your script.

Then run the script.

2017-04-18 13:10 UTC, 153957 requested changes

2017-04-18 13:10 UTC, 153957 commented on migration/config-repair/remove_incorrect_configs.py
> +        config = data.get_node("/hisparc/cluster_"+cluster+"/station_"+str(stationnumber)+"/config")
Use string formatting:
```python
"/hisparc/cluster_{cluster}/station_{stationnumber}/config".format(cluster=cluster, stationnumber=stationnumber)
```

2017-04-18 13:10 UTC, 153957 commented on migration/config-repair/remove_incorrect_configs.py
> +        config.remove_rows(1,len(config))
The end point for [`remove_rows`](http://www.pytables.org/usersguide/libref/structured_storage.html#tables.Table.remove_rows) is optional
> If None all rows after start will be removed.

2017-04-18 13:10 UTC, 153957 commented on migration/config-repair/remove_incorrect_configs.py
> +    remove_configs("2017_4_15.h5", "amsterdam", 4)
Do not forget station 91 on 2017-4-12.

2017-04-18 13:10 UTC, 153957 commented on migration/config-repair/remove_incorrect_configs.py
> +    remove_configs("2017_4_15.h5", "amsterdam", 4)
And perhaps use the full path, or provide a more complete example of how this is to be executed.
Similar to: https://github.com/HiSPARC/datastore/blob/master/migration/migrate_gps_test_data.md#frome-has-an-older-version-of-pytables

2017-04-18 18:04 UTC, 153957 commented
Also add extra explanations to a README/docstrings:
- Why these configurations are going to be removed
- What caused it
- What is not fixed (and why), i.e. the blobs are left.

2017-04-19 09:21 UTC, kaspervd commented
Thanks for the review. I've made the changes and am working on the README. Where in the data file is station 91? Also, should I also place the publicdb repair scripts here?

2017-04-19 09:22 UTC, 153957 commented
You can find the cluster to which 91 belongs here:
http://data.hisparc.nl/api/station/91/

Yes, also add the publicdb cleanup scripts here.

2017-07-07 10:24 UTC, merged